workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    docs-source:
        inputs:
            - location: https://api.unstructured.io/general/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/Unstructured-IO/unstructured-python-client/main/codeSamples.yaml
            - location: https://raw.githubusercontent.com/Unstructured-IO/unstructured-js-client/main/codeSamples.yaml
        output: openapi_with_sdk_codeSamples.yaml
        registry:
            location: registry.speakeasyapi.dev/unstructured/unstructurede4s/docs-source
targets: {}
