workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    docs-source:
        inputs:
            - location: https://raw.githubusercontent.com/Unstructured-IO/unstructured-python-client/main/codeSamples.yaml
        overlays:
            - location: https://raw.githubusercontent.com/Unstructured-IO/unstructured-python-client/main/overlay_client.yaml
        output: openapi.yaml
targets: {}