name: Generate Snippets
'on':
  push:
    tags:
      - '*'
  workflow_dispatch: null
jobs:
  generate-snippets:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Generate Snippets
          run: |
            ./scripts/make_mdx.sh snippets/destination_connectors snippets/source_connectors
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v5
          with:
            token: ${{ secrets.MAKE_PR_TOKEN }}
            add-paths: |
              snippets
            commit-message: Update code snippets
            branch: update-code-snippets/$(git rev-parse --abbrev-ref HEAD)
            title: 'chore: update code snippets'
            assignees: ${{ github.actor }}
            reviewers: ${{ github.actor }}
            delete-branch: true
            body: |
              This automated pull request includes updated code snippets.
            base: ${{ github.head_ref }}